version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sustain_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: V@lidation@uj2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: for initial schema
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Flask Application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_NAME: sustain_app
      DB_USER: postgres
      DB_PASSWORD: V@lidation@uj2025
      DB_HOST: db  # This refers to the db service
      DB_PORT: 5432
      SECRET_KEY: 6ce255c00e63d46c5af17afd44fdccb3
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app  # Mount current directory for development
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  postgres_data:
